# Generated by Django 2.0.4 on 2018-05-04 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(verbose_name='答案文本')),
                ('content', models.TextField(verbose_name='答案')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('votes', models.IntegerField(default=0, verbose_name='赞同数')),
            ],
        ),
    ]
