# Generated by Django 2.0.4 on 2018-05-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='asks.Ask', verbose_name='问题'),
        ),
    ]
