# Generated by Django 2.0.4 on 2018-05-04 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asks', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to=settings.AUTH_USER_MODEL, verbose_name='提问者'),
        ),
        migrations.AddField(
            model_name='ask',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='asks', to='topics.Topic', verbose_name='话题'),
        ),
    ]
